### ISSUE TITLE
Failed to download 5.0.5 + no python3 support

### ISSUE THREAD

**Issue by itayB** [jeffwidman/cqlsh#2]
I saw that you published the new version 3 days ago but `pip install` installing 5.0.4 which doesn't work for me with Python3.
Am I missing something?

**Comment by jeffwidman** [comment]
Yeah, you're looking for version `6.0.0b4`:
* https://github.com/jeffwidman/cqlsh#600b4-mar-9-2021 / 
* https://pypi.org/project/cqlsh/6.0.0b4/
See the notes in the changelog--it is not guaranteed full backwards compatibility with cassandra `3.x`... but it is the first `cqlsh` that supported Python 3.

Version `5.0.5` ships `cqlsh` version `5.0.1` which doesn't support Python 3.

I will release `6.0.0` once upstream `cassandra` ships 4.0 as GA... right now they are still shipping betas. I considered shipping `6.0.0` anyway, but I'd rather wait for GA because then PyPI version `6.0.0` will match the `cqlsh` version: https://github.com/apache/cassandra/commit/021232006c65b31a058735c5cc574096be4e8fe9

Unfortunately the metadata on the old versions `5.0.4` and earlier doesn't explicitly exclude python 3, so they still get pulled down by `pip3`.

I'd like to yank the old releases, at least until Cassandra goes GA (and then can unyank them so they're visible to anyone who wishes to pull them down explicitly) but I don't have the proper permissions--when I was added as a maintainer on PyPI I was only given upload rights, not version management rights--I just fired an email to @aboudreault requesting to be made an admin so I can make this easier on folks.

**Comment by aboudreault** [comment]
I've yanked the old releases. So users will now get a message to install 6.0.0b4 for Python3.

**Comment by jeffwidman** [comment]
Thanks @aboudreault!

**Comment by itayB** [comment]
just had a chance to test it but it breaks too quick :(
trying to run the following command via script:
```
cqlsh <my_scylla_hostname> -e "describe keyspaces;"
```
and I'm getting:
```
/usr/local/bin/cqlsh:470: DeprecationWarning: Legacy execution parameters will be removed in 4.0. Consider using execution profiles.
/usr/local/bin/cqlsh:500: DeprecationWarning: Setting the consistency level at the session level will be removed in 4.0. Consider using execution profiles and setting the desired consitency level to the EXEC_PROFILE_DEFAULT profile.
<stdin>:1:
```
any idea how can I use the execute flag in the new version? (6.0.0b4)
```
  -e EXECUTE, --execute=EXECUTE
                        Execute the statement and quit.
```

**Comment by aboudreault** [comment]
the warnings aren't error so I don't see the real issue and if your query was executed. You should probably create a ticket in the cassandra jira. This project is just packaging cqlsh from the cassandra project and publish it on pypi.
